### ISSUE TITLE
Support for URL query parameters to link directly to a chart page

### ISSUE THREAD

**Issue by tlemane** [serratus-bio/open-virome#151]
### What would you like to be added?

Hi,

Congrats for OpenVirome!

It would be very useful to have a way to load an open virome page directly from a link, for example: [http://openvirome.com/?BioProject=PRJNA385854](http://openvirome.com/?BioProject=PRJNA385854)

Thanks!

### Why is this needed?

I'm working on Logan Search and we would like to provide direct links to Open Virome for RunID, BioSample, and BioProject in our web interface.

**Comment by lukepereira** [comment]
I think a simple feature of supporting single SRA identifiers in URL params is a good first step!

We got caught up in wanting to support more complex URLs that would include different metadata filters like `?tissue=x`, or lists of ids and filters which made us lean toward generating a session id because of the limitations of url lengths.

@ababaian supporting single ids would be easy, lists of ids is also do-able but would break for larger datasets. LMK what you think and I can add this next week

**Comment by ababaian** [comment]
Can we support an array URL input of upto say 10 identifiers? After that I think it will require a POST which can/should be a different issue. Another way is if we decide on a standard `sralist` format with some simple parameters, and then we can export/import files between services in a relatively straightforward manner.

For first pass, I'd say the simplest of single/short array input we can/should prioritize now

**Comment by lukepereira** [comment]
I found [a lightweight js package](https://github.com/Treora/redux-query-sync) that handles syncing url params with app state and pushed a first pass of using the filter state.

Unfortunately, it's not easy to get it to match the format of `/?{filterName}={filterValue}` and has URLs of the form `/?filters=["{filterName}-{filterValue}"]`. So for SRA Ids, this looks like:
- https://openvirome.com/?filters=["bioproject-PRJDB7399"]
- https://openvirome.com/?filters=["bioproject-PRJDB7399","bioproject-PRJEB31530","bioproject-PRJNA708320"]
- https://openvirome.com/?filters=["biosample-SAMN03761369"]
- https://openvirome.com/?filters=["runId-SRR2063967"]

IMO this isn't is a blocker, but let me know if you disagree or notice other bugs. I didn't put a limit on how large this list can be since it works for a fairly large number of ids/filters.

We can track future improvements/ideas in the [other existing issue](https://github.com/serratus-bio/open-virome/issues/23)

**Comment by tlemane** [comment]
Nice! I'll let you know if I find any strange behavior, but everything seems fine. Thanks!

**Comment by lukepereira** [comment]
Awesome, btw where can I find the LoganSearch github repo? @tlemane

**Comment by lukepereira** [comment]
This seems to be stable now so i'm going to close it. 

For reference:
We found an issue earlier when adding filters for ids that didn't exist, the app still showed data. This was resolved by adding a "no results message" (e.g. https://openvirome.com/?filters=["runId-SRR9860226"])

I also added support for toggling query behaviour to include runs with no virus data. You can make this the default by adding a query parameter `&palmprintOnly=false`, otherwise users can click to change it on the no results message.

After we run palmdbv3 on Logan data there should be a lot more virus hits so the current behaviour is probably fine.
