### ISSUE TITLE
Update Menu Labels

### ISSUE THREAD

**Issue by ababaian** [serratus-bio/open-virome#33]
![image](https://github.com/serratus-bio/open-virome/assets/9220907/6082d0e5-162b-4ac2-b297-2202ce1479a8)

**Comment by ababaian** [comment]
For the Virome Module, `Virus Species, sOTU, and Virus Family` should all be merged into `Virome Network` as a single tab, and changing the color scheme on the graph should be a radio button within the main window 

![image](https://github.com/serratus-bio/open-virome/assets/9220907/01f11fcb-5947-4c71-8e34-ef97d86bdcaa)

**Comment by lukepereira** [comment]
It seems useful to allow adding different filters for sOTU, species, family, so I'm not sure we should merge them together. 

btw, changing the selection should also change the graph construction and not only color.

Overall, I think we should do a proper design review (possibly with a hired designer) and make a more cohesive plan since i can see some inconsistencies with some of the suggested changes and some interaction issues

**Comment by ababaian** [comment]
The query-builder should be entirely abstracted away from the display of figures. Having that do both is where the inconsistency is coming from. I'm all for getting a UX designer on board, but right now there's some fundamentals that need to  be hashed out
