### ISSUE TITLE
[Feature] Refactor map-ui to display `contigs` (graph edge) not BioSamples

### ISSUE THREAD

**Issue by almosnow** [serratus-bio/open-virome#53]
... because we ultimately want a map of the molecular evidence of an occurrence of a virus, not a map of the experiments that were performed

**Comment by lukepereira** [comment]
Currently the map shows biosamples that match what the user searched for, which could be virus related or other metadata 

I think the contigs will tie in if/when we integrate the app with the kmindex which is in development. Then user's can enter any sequence and kmindex would return contigs and SRA accessions with matching kmers and those can be used as the identifiers

**Comment by ababaian** [comment]
As per the Virome data-model, the unit of data which is being represented in the interface is individual `contig` which are grouped into virus sOTU 
![image](https://github.com/user-attachments/assets/c692485c-a06b-4b23-b0f4-cba8c5091036)

See: https://github.com/serratus-bio/open-virome/wiki/Virome

To display the geospatial distribution, it makes sense to represent each `contig` as a point on the graph, which will allow for things such as "Virus Identity Filtering" or "Virus class filtering" and better capture the density of virus-observation per unit geography.


This is going to require a `JOIN` operation most likely on the datasets which can be rendered (and their lat/lon) and the data which is already calculated in the virome modules.

**Comment by ababaian** [comment]
Please add a `Time Estimate:` for this issue.

**Comment by almosnow** [comment]
This is a small sub-project on its own.

@ababaian you want me to draft all the subtasks?

They're more or less:
 
* Set up the data/tables to support this (easiest would be to just add a list of reads to the lat_lon materialized view).
* Make the map render the contigs (or the biosamples w/ a contig count inside of them)
* Update the tooltips to show the list of contigs and their sequence.

**Comment by ababaian** [comment]
That's the right level of analysis yes, each of those sub-tasks should be given a time estimate and that will provide us with an overall time estimate for this task. This is exactly the information which we would want to have thought out upfront when opening such an issue so that it can allow for planning and execution of this in an efficient manner. Let's indeed use this as an example issue for planning out the logistics; feel free to edit the main issue post here and provide the plan for execution.

**Comment by ababaian** [comment]
Contig feature is looking good! some notes


![Image](https://github.com/user-attachments/assets/e016ff3c-2e12-4295-a112-a6fe5191ecbf)
- [x] `Run` should be moved up to the first tab which relates to the "SRA Run Info" for a given point.

![Image](https://github.com/user-attachments/assets/81382e83-faa2-4fe0-8e94-53e484c5c3b4)
- [ ] Is the reported amino acid sequence the `palmprint` from exactly that virome; or is it the `sOTU` sequence of the representative virus? The specific sequence reported should be the sequence of exactly that contig; and `palmprint` sOTU number put into the header
- [x] Add underscore after `coverage` should read `coverage_14`

![Image](https://github.com/user-attachments/assets/cd721e2e-ed66-4fa6-b8d7-97465f973f62)
- [x] Add `BLAST` link-out button to take the input sequence and query it on BLAST `nr`; code exists in the Graph module already for this

![Image](https://github.com/user-attachments/assets/7d126901-1b8b-402e-9166-4f6ce254cf23)
- [x] For the fasta sequence; wrap newline at 30 characters so that there is no horizontal scrolling needed and the whole palmprint is displayed within the box.

**Comment by almosnow** [comment]
>Is the reported amino acid sequence the palmprint from exactly that virome.

It is the palmprint for that virome.

**Comment by ababaian** [comment]
Sorry one more detail for this: Can you make `contigs` the "Default" view for Open Virome. This will ensure the presentation of information across the project is as uniform as possible and people don't have to think about how the data representation changes per module.

- [x] Change `contigs` to default.

**Comment by ababaian** [comment]
Related: `Showing 32 geographic sites for 25 palmprints, 25 sOTUs on 87 hits.`

Can this be amended to
```
Showing 32 geographic locations for 87/<Total Contigs> contigs, representing 25/<Total unique sOTU> sOTU, from XX/<Total unique runs> libraries.
```

- [x] Amend reporting info sentence.

**Comment by ababaian** [comment]
- [x] Checksum the summary statement *discussion / bugfix*

**Comment by ababaian** [comment]
- [x] Remove the `newline` when reporting data so that the side-panel on the map is consistently `Field: Value`  

![Image](https://github.com/user-attachments/assets/4a011802-f7a7-4d62-953c-555d11bd2578)

**Comment by ababaian** [comment]
Refactor sentence when using `samples` as display points
![Image](https://github.com/user-attachments/assets/2cab58be-3fd0-498d-9b0a-b4f0ac946d2f)

**Comment by ababaian** [comment]
- [ ] Dim property names to fade them into the back slightly
- [ ] Add blue-text linkout like in Virome module
- [ ] Add 'Scientific_name' under the `Run id`
- [ ] Remove redundant `sample name` from under BioProject

![Image](https://github.com/user-attachments/assets/5ba9f213-80b8-44c7-9bbe-3f773b3d08a4)
![Image](https://github.com/user-attachments/assets/6c8ae961-b465-4e58-9fbc-f74eba95ad32)

**Comment by ababaian** [comment]
@almosnow  I'll close this issue, can you open a low priority issue for hte above "UI improvements" for the map module for this sprint.
