### ISSUE TITLE
bug: Error parsing JSON response SyntaxError: Unexpected token 'W', "W3siY291bn"... is not valid JSON

### ISSUE THREAD

**Issue by almosnow** [serratus-bio/open-virome#87]
Calls to `https://zrdbegawce.execute-api.us-east-1.amazonaws.com/prod/counts` return errors like the one in the subject.

 That string is base64 encoded so maybe a missing `atob(...)` call somewhere?

**Comment by lukepereira** [comment]
the RTK client already has a line for parsing this. https://github.com/serratus-bio/open-virome/blob/ab7e2c0d451c2fced2af32b72e2669ece5f1113d/frontend/src/api/client.ts#L23 

Can remove the error message from console if it's too noisy. I couldn't figure out why api-gateway was base64 encoding the request sometimes.

Also, we should try using that client instead of using fetch since it will handle UI caching, retries, etc

**Comment by ababaian** [comment]
Is there something actionable here?

**Comment by lukepereira** [comment]
Hey @almosnow, just checked that the error message when using the RTK api client is correctly being parsed, e.g.:
```
{"error":"{\"errno\":-3008,\"code\":\"ENOTFOUND\",\"syscall\":\"getaddrinfo\",\"hostname\":\"serratus-aurora-20210406.cluster-ro-xc.us-east-1.rds.amazonaws.com\"}"}
```

I'm thinking the issue you had was from calling the api directly without using the client and not adding the atob parsing. Since it's being handled throughout the app, i don't think this requires any changes.

LMK if there is some other issue you were talking about and I can take a look

**Comment by moralestapia** [comment]
>I'm thinking the issue you had was from calling the api directly without using the client and not adding the atob parsing.

No, it's all over the place when you open the developer console, pic:

![image](https://github.com/user-attachments/assets/fc90372c-e321-42c6-a647-9be9880b4136)

**Comment by lukepereira** [comment]
Ohh, okay. This is just a logging issue - i removed the console.error statements.
